dataset:
  dataset: datasets.minst_dataset.MinstBnBDataset
  is_visualise: False
  n_data: 60000
  img_training_size: 200
  use_collate: True
train:
  trainer: trainers.bnb_trainer.Trainer
  batch_size: 3
  ckpt_freq: 1
  device: cuda
  epochs: 30
  loss_file: loss.txt
  lr: 0.00005
  model_file: ckpts/pytorch_model
  num_workers: 0
  optimizer: torch.optim.AdamW
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 5
  scheduler_threshold: 0.0001
  scheduler_verbose: True
  shuffle: True
  eval_step: 1000
model:
  model: models.frcnn.FRCNNMobileNet
  ckpt: null
