dataset:
  dataset: datasets.minst_dataset.MinstDensityDataset
  is_visualise: False
  n_data: 60000
  img_training_size: 200
  use_collate: False
train:
  trainer: trainers.density_trainer.Trainer
  batch_size: 4
  ckpt_freq: 1
  device: cuda
  epochs: 30
  loss_file: loss.txt
  lr: 0.00005
  model_file: ckpts/pytorch_model
  num_workers: 0
  optimizer: torch.optim.AdamW
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_params:
    factor: 0.5
    patience: 5
    threshold: 0.0001
    verbose: True
  shuffle: True
  eval_step: 1000
model:
  model: models.unet.UNet
  in_channels: 1
  out_channels: 2
  ckpt: null
