dataset:
  dataset: datasets.minst_dataset.MinstBnBDataset
  is_visualise: False
  n_data: 60000
  img_training_size: 200
  use_collate: True
train:
  trainer: trainers.bnb_trainer.Trainer
  batch_size: 64
  ckpt_freq: 1
  device: cuda
  epochs: 300000
  loss_file: loss.txt
  lr: 0.003
  model_file: ckpts/pytorch_model
  num_workers: 0
  optimizer: torch.optim.AdamW
  scheduler: torch.optim.lr_scheduler.MultiStepLR
  scheduler_params: 
    milestones: [240000]
    gamma: 0.1
    verbose: True
  shuffle: True
  eval_step: 1000
model:
  model: models.frcnn.FRCNNMobileNet
  ckpt: null
