dataset:
  dataset: datasets.minst_dataset.MinstBnBDataset
  is_visualise: False
  n_data: 60000
  img_training_size: 200
  use_collate: True
train:
  trainer: trainers.bnb_trainer.Trainer
  ckpt_freq: 1
  device: cuda
  epochs: 300000
  loss_file: loss.txt
  model_file: ckpts/pytorch_model
  eval_step: 1000
  dataloader_params:
    num_workers: 0
    shuffle: True
    batch_size: 64
  optimizer: torch.optim.AdamW
  optimizer_params:
    lr: 0.003
  scheduler: torch.optim.lr_scheduler.MultiStepLR
  scheduler_params: 
    milestones: [240000]
    gamma: 0.1
    verbose: True
model:
  model: models.frcnn.FRCNNMobileNet
  ckpt: null
