dataset:
  dataset: datasets.minst_dataset.MinstSegDataset
  is_visualise: False
  n_data: 60000
  img_training_size: 200
  use_collate: False
  n_classes: 2
train:
  trainer: trainers.seg_trainer.Trainer
  ckpt_freq: 1
  device: cuda
  epochs: 30
  loss_file: loss.txt
  model_file: ckpts/pytorch_model
  eval_step: 1000
  dataloader_params:
    num_workers: 4
    shuffle: True
    batch_size: 16
  optimizer: torch.optim.RMSprop
  optimizer_params:
    lr: 0.00001
    weight_decay: 0.00000001
    momentum: 0.9
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_params:
    mode: max
    patience: 2
    verbose: True
model:
  model: models.unet.UNet
  in_channels: 1
  out_channels: 2
  ckpt: null
