dataset:
  dataset: datasets.character_dataset.CharacterRecDataset
  is_visualise: False
  n_data: 60000
  use_collate: False
  n_char: 10 # Increase to 10 characters
  n_classes: 24 # 13 characters + 1 EOF token
train:
  trainer: trainers.rec_seq_trainer.Trainer
  ckpt_freq: 1
  device: cuda
  epochs: 300
  loss_file: loss.txt
  model_file: ckpts/pytorch_model
  eval_step: 1000
  dataloader_params:
    num_workers: 8
    shuffle: True
    batch_size: 64
  optimizer: torch.optim.AdamW
  optimizer_params:
    lr: 0.001
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_params:
    mode: min
    patience: 5
    verbose: True
model:
  model: models.charnet.CharSeqNet
  in_channels: 1
  n_char: 10 # Increase to 10 characters
  n_classes: 24
  ckpt: null
